-- UP
ALTER TABLE conversas ADD COLUMN IF NOT EXISTS lida BOOLEAN DEFAULT false;
ALTER TABLE conversas ADD COLUMN IF NOT EXISTS lida_em TIMESTAMPTZ;
ALTER TABLE conversas ADD COLUMN IF NOT EXISTS lida_por UUID REFERENCES usuarios(id);
